/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CreateFileModal: typeof import('./src/components/CreateFileModal.vue')['default']
    CreateFolderModal: typeof import('./src/components/CreateFolderModal.vue')['default']
    DeleteConfirmModal: typeof import('./src/components/DeleteConfirmModal.vue')['default']
    EditFileModal: typeof import('./src/components/EditFileModal.vue')['default']
    EditFolderModal: typeof import('./src/components/EditFolderModal.vue')['default']
    FolderTree: typeof import('./src/components/FolderTree.vue')['default']
    FolderTreeNode: typeof import('./src/components/FolderTreeNode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
